### ISSUE TITLE
Incompatibility with EC-Lab>=11.50 - BioLogic.MPRfile issue

### ISSUE THREAD

**Issue by Dongrun7** [echemdata/galvani#87] opened 2023-06-27 14:39 UTC
I tried to use BioLogic.MPRfile() to open the data but it seems can not read raw mpr data 

 raise IOError("""Unexpected end of file while reading data
OSError: Unexpected end of file while reading data
                    current module: b'VMP settings             '
                    length read: 20759
                    length expected: 4294967295

**Comment by d-cogswell** [comment] 2023-06-28 17:55
I'm also seeing this error with mpr files from the newest version of EC-Lab.

**Comment by dansteingart** [comment] 2023-06-29 03:16
It seems somewhat low-level: the `VMPmodule_hdr` length conditions in galvani and new ec-lab`.mpr` files. I pulled and added debug comments to `BioLogic.py`, so @Dongrun7's error above is reproduced

```
VMPmodule_hdr = np.dtype([('shortname', 'S10'),
                          ('longname', 'S25'),
                          ('length', '<u4'),
                          ('version', '<u4'),
                          ('date', 'S8')])

```

yields

```
b'VMP Set   VMP settings             \xff\xff\xff\xffa\x1a\x00\x00\x00\x00\x00\x00\n\x00\x00\x00'
{'shortname': b'VMP Set   ', 'longname': b'VMP settings             ', 'length': 4294967295, 'version': 6753, 'date': b'\x00\x00\x00\x00\n'}
109
Traceback (most recent call last):
  File "/Users/dan/Code/pithy/code/DS_galvani_futz_2.py", line 22, in 
    mpr_file = MPRfile(fns[0])

  File "/Users/dan/Code/pithy/code/DS_galvani_pull.py", line 403, in __init__
    modules = list(read_VMP_modules(mpr_file))
  File "/Users/dan/Code/pithy/code/DS_galvani_pull.py", line 362, in read_VMP_modules
    raise IOError("""Unexpected end of file while reading data
OSError: Unexpected end of file while reading data
                    current module: b'VMP settings             '
                    length read: 489056
                    length expected: 4294967295
```

Examining `hdr_data` we see the date is nonsensical, and it seems `date` is 8 bytes further out from `longname`

Through some trial and error in modifying `VMPmodule_hdr` I was able to get the code to step further...

```
VMPmodule_hdr = np.dtype([('shortname', 'S10'),
                          ('longname', 'S25'),
                          ('whoknows', 'S4'),
                          ('length', '<u8'),
                          ('version', '<u4'),
                          ('date', 'S8')])
```

but then gets hung up on versioning

```
b'VMP Set   VMP settings             \xff\xff\xff\xffa\x1a\x00\x00\x00\x00\x00\x00\n\x00\x00\x0006/21/23'
{'shortname': b'VMP Set   ', 'longname': b'VMP settings             ', 'holder': b'\xff\xff\xff\xff', 'length': 6753, 'version': 10, 'date': b'06/21/23'}
117
b'VMP data  VMP data                 \xff\xff\xff\xffW:\x07\x00\x00\x00\x00\x00\x0b\x00\x00\x0006/21/23'
{'shortname': b'VMP data  ', 'longname': b'VMP data                 ', 'holder': b'\xff\xff\xff\xff', 'length': 473687, 'version': 11, 'date': b'06/21/23'}
6935
b'VMP LOG   VMP LOG                  \xff\xff\xff\xff\xad\x1f\x00\x00\x00\x00\x00\x00\n\x00\x00\x0006/22/23'
{'shortname': b'VMP LOG   ', 'longname': b'VMP LOG                  ', 'holder': b'\xff\xff\xff\xff', 'length': 8109, 'version': 10, 'date': b'06/22/23'}
480687
b'VMP loop  VMP expt. loop indexes   \xff\xff\xff\xff0\x01\x00\x00\x00\x00\x00\x00\n\x00\x00\x0006/22/23'
{'shortname': b'VMP loop  ', 'longname': b'VMP expt. loop indexes   ', 'holder': b'\xff\xff\xff\xff', 'length': 304, 'version': 10, 'date': b'06/22/23'}
488861
Traceback (most recent call last):
  File "/Users/dan/Code/pithy/code/DS_galvani_futz_2.py", line 22, in 
    mpr_file = MPRfile(fns[0])
  File "/Users/dan/Code/pithy/code/DS_galvani_pull.py", line 430, in __init__
    raise ValueError("Unrecognised version for data module: %d" %
ValueError: Unrecognised version for data module: 11
```

I'm guessing a root cause is how `VMPmodule_hdr` is constructed, but I'm stumped after this

**Comment by d-cogswell** [comment] 2023-06-29 21:18
Looks like the new version of EC-Lab might be outputting a new file version.

**Comment by dansteingart** [comment] 2023-06-30 03:22
yeah, trying to figure out what the specific difference is. @d-cogswell do you have a link to the old version of EC-Lab? I want to downgrade until this gets licked.

**Comment by BradyPlanden** [comment] 2023-07-21 07:27
Has anyone found a workaround for this over the last few weeks?

**Comment by NuxitBrain** [comment] 2023-07-21 14:29
> yeah, trying to figure out what the specific difference is. @d-cogswell do you have a link to the old version of EC-Lab? I want to downgrade until this gets licked.

Hi ! i'm principally a user of the mpr module and i starded to see this error ... If your interested in, i have some old excutable of ec-lab (11.46 and 11.41) and bt-lab (1.73). 
Also, if you only want data made with the older version, i think i can provide you data made with the version 11.46 (the one currently installed in your lab)

**Comment by BradyPlanden** [comment] 2023-08-08 10:36
For visability, I reached out to BioLogic to confirm it is a MPR filetype change. Here is the response,

> We have now heard back from our technical team and the product manager.
>  
> Apparently, they needed to change the mpr files structure a little so they can manage a larger amount of data.
> Unfortunately, they are not allowed to provide the keys to the change (even though they know that someone will work it out eventually anyway) but you should be ok to continue using the earlier versions.
 
Rebuilding the keys manually everytime they decide to change the structure is quite the hassle. Does anyone have ideas or tools to reduce this overhead?

**Comment by ml-evs** [comment] 2023-08-08 16:15
> For confirmation, I reached out to BioLogic to confirm it is a MPR filetype change. Here is their response,

Thanks for this!

> Rebuilding the keys manually everytime they decide to change the structure is quite the hassle. Does anyone have ideas or tools to reduce this overhead?

Just connecting some dots here from other issues I've seen, but it looks like some progress was made in https://github.com/echemdata/galvani/issues/80 by analyzing the actual .exe and extracting structure. Might be more robust than manual updates. I'm happy to help out with this if there is interest.

**Comment by fg-personal** [comment] 2023-09-25 09:50
I have also encountered this problem. Has anyone found workarounds?

**Comment by fg-personal** [comment] 2023-09-25 12:21
Has anyone found a workaround over the last few weeks? 
I tried the script below to quickly decode the exe
[extract_info_hopefully_fromECLab_exe.py.txt](https://github.com/echemdata/galvani/files/12714917/extract_info_hopefully_fromECLab_exe.py.txt)
I quickly found something by using 
"grep -i -C 170 "Z'/ohm" extracted_raw_text.txt > exe_interesting_lines.txt" (the txt file is the output of the script below)

Here's the result of my search:
[exe_interesting_lines.txt](https://github.com/echemdata/galvani/files/12714906/exe_interesting_lines.txt)
although I am not sure about how to implement this

Does anyone have ideas about how to proceed?

**Comment by PeterKraus** [comment] 2023-09-26 08:26
My plan for fixing this in [`yadg`](https://github.com/dgbowl/yadg) was to get a hand on a set of MPR and MPT files generated in 11.50 using the same experiments. I don't have access to any biologic hardware right now, and not much time to work on this. But getting such files, at least for the "basic methods" (constant current, constant voltage) might be a good start.

**Comment by fg-personal** [comment] 2023-09-27 09:30
@PeterKraus, thanks for the interest in this topic. I would be happy to find a python-based open-source solution to parse potentiostat files and a user I know may be willing to share the files you mention with people that already have EC-Lab software on their pc. 
Despite the kind reply from the BioLogic technical team (...they know that someone will work it out eventually anyway...), I do want to re-emphasize the importance of handling the data with care and respecting any potential restrictions.

**Comment by tk-4767** [comment] 2023-09-27 13:11
@PeterKraus, here is Data of a Dummy Cell from the newest version (11.50). [DC_3_VMP3_02_CV.zip](https://github.com/echemdata/galvani/files/12738923/DC_3_VMP3_02_CV.zip)
I can provide you more data if needed.

**Comment by fg-personal** [comment] 2023-09-28 13:30
@PeterKraus, here is Data for a dummy resistor (2-electrode config) from the newest version (11.50)
[15MOhm EC Lab 11.50 galvani.zip](https://github.com/echemdata/galvani/files/12749887/15MOhm.EC.Lab.11.50.galvani.zip)
Some metadata has been removed in a text editor, now the files do not open in EC-Lab anymore for some reason, but all the measurement data should still be intact.

**Comment by PeterKraus** [comment] 2023-09-29 08:01
Thanks for the files, @fg-personal and @tk-4767. I might have someone to take this project up in the coming weeks. I'll keep you posted.

**Comment by fg-personal** [comment] 2023-10-02 15:14
is this problem completely absent for files created in slightly older EC-Lab versions (e.g. 11.46 or 11.47)?

**Comment by tk-4767** [comment] 2023-10-02 15:44
With files from version 11.48 I never had a problem

**Comment by fg-personal** [comment] 2023-10-02 22:28
I have been trying to use the mpt reader function from galvani, after an mpr→mpt conversion in EC-Lab. 

This process helped me to identify some new field names:

I had to modify:
```python
def fieldname_to_dtype(fieldname):
    """Converts a column header from the MPT file into a tuple of
    canonical name and appropriate numpy dtype"""

    if fieldname == 'mode':
        return ('mode', np.uint8)
    elif fieldname in ("ox/red", "error", "control changes", "Ns changes",
                       "counter inc."):
        return (fieldname, np.bool_)
    elif fieldname in ("time/s", "P/W", "(Q-Qo)/mA.h", "x", "control/V",
                       "control/V/mA", "(Q-Qo)/C", "dQ/C", "freq/Hz",
                       "|Ewe|/V", "|I|/A", "Phase(Z)/deg", "|Z|/Ohm",
                       "Re(Z)/Ohm", "-Im(Z)/Ohm",  #new entries after this
                       "step time/s",  "Cs/uF", "Cp/uF", "Re(Y)/Ohm-1", "Im(Y)/Ohm-1",
                       "|Y|/Ohm-1", "Phase(Y)/deg", "Re(C)/nF", "Im(C)/nF",
                       "|C|/nF", "Phase(C)/deg", "Re(M)", "Im(M)", "|M|",
                       "Phase(M)/deg", "Re(Permittivity)", "Im(Permittivity)",
                       "|Permittivity|", "Phase(Permittivity)/deg", "Re(Resistivity)/Ohm.cm",
                       "Im(Resistivity)/Ohm.cm", "|Resistivity|/Ohm.cm", "Phase(Resistivity)/deg",
                       "Re(Conductivity)/mS/cm", "Im(Conductivity)/mS/cm", "|Conductivity|/mS/cm",
                       "Phase(Conductivity)/deg", "Tan(Delta)", "Loss Angle(Delta)/deg",
                       "Cs-2/uF-2", "Cp-2/uF-2"):
        return (fieldname, np.float_)
    elif fieldname in ("cycle number", "I Range", "Ns", "half cycle"):
        return (fieldname, np.int_)
    elif fieldname in ("dq/mA.h", "dQ/mA.h"):
        return ("dQ/mA.h", np.float_)
    elif fieldname in ("I/mA", "<I>/mA"):
        return ("I/mA", np.float_)
    elif fieldname in ("Ewe/V", "<Ewe>/V"):
        return ("Ewe/V", np.float_)
    else:
        raise ValueError("Invalid column header: %s" % fieldname)
    # added "step time/s", (present in CV files)
    # added "Cs/uF", "Cp/uF", "Re(Y)/Ohm-1", "Im(Y)/Ohm-1",... (present in EIS files)
```


I have also changed the line
```python
fieldnames = next(mpt_file).decode(encoding).strip().split('\t')
```
to 
```python
fieldnames = next(mpt_file).replace(b'\xb5', b'u').decode(encoding).strip().split('\t')
```
to get rid of the μ, not interpreted very well by the software


As I try to import mpt files in python and to put them into dataframes
```python
mpt = BL.MPTfile(filename_with_path)
df = pd.DataFrame(mpt[0])
```
I get slightly different headers depending on the EC-Lab version used to generate the original mpr file: [EIS examples](https://diff.cnbeining.com/v1/diff#H4sIAAAAAAAAA51SXW_aMBT9K5b3QiRIyKQ-tH5CaashlbUwNIlSVBl8SSzFDovNGKv332fHNoOqT3uxr8859_j44w0zvt3im-Vy2Md3xeCBrhFe9ZeDvI8_u8LOeZ5eudIqhpHLrwOCKqAMWoU4A6n5lgND6yPSFSDRML-2Q80kFfCqm1emjzvoJSmaO8lOW7YGdKAKlSChpdo2KE1bzWWJtm0jEJXofbJhjBZS5JG5DkR6NYwBxa71e3DZxfqvU6pmqw-0hfRFvshPNhf8yL78JjPoPSfZYyXIYCxiaZ5NNz9VVHU8g5JoLiBT5O4A2XcyzsSIFCrb35Ni58bNcWMDyr1YQ0vGaEZlCcRYsbFqMzbZKKQkX1WIRHrTwbRJrFNauRyLbvNBTmyQU20WJlQ-zCLY-Ey2q0gyee9afGEK4yYvLk6qSeIkdjQTE8jJiXyCVnCt-U-uj53uEjDny9h9IYlGM1BcRcymTjfC2X0EmzPQRNBbX8jjKRvJ9psIim-Zd_4INuegCWC4jwu5s55T2buFWtOEPDRKoZEsa_BIeCWvY9PumfBq1cd1pez3gxrf4MeWl1zSGs3hl8Z93P6jisp9AeaZP38B9bbs96YDAAA)
I have the impression the mpt interpreter hasn't been updated in a while. I had errors while importing EIS files made with an EC-Lab version from 2019 ("Cs/uF", "Cp/uF" not recognized as valid entries) and I had to use the modified fieldname_to_dtype even for files this old.

**Comment by schaubhoffmann** [comment] 2023-10-11 10:15
I am not working with EC-lab, but was asked by a collegue to tweak the Biologic.py to make it work for the data from EC-Lab 11.50. I have only used it on a few files so far and it definitely needs further testing. But as someone else might already be working on it, here is what I did so far:

I had to change the VMP_Module_hdr (similar to  @dansteingart): 

```
VMPmodule_hdr = np.dtype([('shortname', 'S10'),
                          ('longname', 'S25'),
                          ('something', '<u4'),
                          ('length', '<u4'),
                          ('somethingelse', '<u4'),
                          ('version', '<u4'),   
                          ('date', 'S8')])
```
						  
Not sure if should be like this or like @dansteingart's - for the files I tested it does not make a difference. 
Either way I end up with version numbers 10 for the Data Module and Log Module and 11 for the Data Module, which seems plausible for a new data format.

The initialization of the MPRfile class now of course needs to include the condition `data_module['version'] == 11` in the if-statement for the Data Module version. The number of bytes of data before the main data array seems to have changed to 1007.
Like in Data Module version 3 there is a '\x01' before the start of the data.

So this is how it works for our data so far:

```
# this is for EC-LAB 11.50. data_module version == 11
elif data_module['version'] == 11: 
            column_types = np.frombuffer(data_module['data'][6:], dtype='<u2',
                                         count=n_columns)
            # There are bytes of data before the main array starts
            num_bytes_before = 1007  
            remaining_headers = data_module['data'][6 + 2 * n_columns:num_bytes_before-1]
            main_data = data_module['data'][num_bytes_before:]
```
			
I will now have the people actually working with EC-Lab test it.

**Comment by ml-evs** [comment] 2023-10-11 11:24
Thanks for all the suggestions + data sharing here! I think this shows how widely used galvani still is, so we should put in some effort to ensure its ongoing maintenance. Does anyone have a line on @chatcannon so we could potentially get some maintainers added to the repo? (I guess naturally that means I volunteer but would prefer not to do it alone...) To avoid hijacking this issue I will raise a new one based on this comment, but just wanted to encourage people from this discussion to think about it!

**Comment by fg-personal** [comment] 2023-11-06 10:52
> I am not working with EC-lab, but was asked by a collegue to tweak the Biologic.py to make it work for the data from EC-Lab 11.50. I have only used it on a few files so far and it definitely needs further testing. But as someone else might already be working on it, here is what I did so far:
> 
> I had to change the VMP_Module_hdr (similar to @dansteingart):
> 
> ```
> VMPmodule_hdr = np.dtype([('shortname', 'S10'),
>                           ('longname', 'S25'),
>                           ('something', '<u4'),
>                           ('length', '<u4'),
>                           ('somethingelse', '<u4'),
>                           ('version', '<u4'),   
>                           ('date', 'S8')])
> ```
> 
> Not sure if should be like this or like @dansteingart's - for the files I tested it does not make a difference. Either way I end up with version numbers 10 for the Data Module and Log Module and 11 for the Data Module, which seems plausible for a new data format.
> 
> The initialization of the MPRfile class now of course needs to include the condition `data_module['version'] == 11` in the if-statement for the Data Module version. The number of bytes of data before the main data array seems to have changed to 1007. Like in Data Module version 3 there is a '\x01' before the start of the data.
> 
> So this is how it works for our data so far:
> 
> ```
> # this is for EC-LAB 11.50. data_module version == 11
> elif data_module['version'] == 11: 
>             column_types = np.frombuffer(data_module['data'][6:], dtype='<u2',
>                                          count=n_columns)
>             # There are bytes of data before the main array starts
>             num_bytes_before = 1007  
>             remaining_headers = data_module['data'][6 + 2 * n_columns:num_bytes_before-1]
>             main_data = data_module['data'][num_bytes_before:]
> ```
> 
> I will now have the people actually working with EC-Lab test it.

Seems promising but I still got some errors:
loop_module['version'] is not equal to 0 anymore and that raises the 
`ValueError("Unrecognised version for data module: %d" %data_module['version'])`
That's a red flag, but allowing: loop_module['version'] to be 10 without raising the error seems to solve the problem. I haven't checked this extensively but the first tests I made look good.

With schaubhoffmann's changes to Biologic.py, the script doesn't work for files created with EC-Lab 11.46 or lower
`ValueError: Found b'\x00\x00\x00\x00\x00\x00', expecting start of new VMP MODULE
While in the read_VMP_modules function`

For the moment, I will keep both a Biologic.py (original file) and a Biologic_SH.py (edits from schaubhoffmann) and switch from one to the other with try and except.

**Comment by jojo-Li2** [comment] 2024-01-09 11:42
My way of tweaking it and stay compatible with earlier versions was to define 2 different VMPmodule_hdr :

```
VMPmodule_hdr_v2 = np.dtype(
    [
        ("shortname", "S10"),
        ("longname", "S25"),
        ("unknown1", "<u4"),
        ("length", "<u4"),
        ("version", "<u4"),
        ("unknown2", "<u4"),
        ("date", "S8"),
    ]
)

VMPmodule_hdr_v1 = np.dtype(
    [
        ("shortname", "S10"),
        ("longname", "S25"),
        ("length", "<u4"),
        ("version", "<u4"),
        ("date", "S8"),
    ]
)
```
We first read headers with the v1 structure, and if it corresponds to v11.50 files we read 8 additional bytes.
The "unknown1" in v11.50 files seems to always be b"\xff\xff\xff\xff". So we can modify the read_VMP_modules function :
```
# Excpecting EC-Lab version < 11.50
VMPmodule_hdr = VMPmodule_hdr_v1

# Reading headers binary information
hdr_bytes = fileobj.read(VMPmodule_hdr.itemsize)
if len(hdr_bytes) < VMPmodule_hdr.itemsize:
    raise IOError("Unexpected end of file while reading module header")

# Checking if EC-Lab version is >= 11.50
if hdr_bytes[35:39] == b"\xff\xff\xff\xff":
    VMPmodule_hdr = VMPmodule_hdr_v2
    hdr_bytes += fileobj.read(VMPmodule_hdr_v2.itemsize - VMPmodule_hdr_v1.itemsize)
```
I haven't had the occasion to test it with a lot of different techniques (only OCV and PEIS), but in those cases :

-  "version" was always 0
-  "unknown2" was always 10 for settings, log and loop modules and 11 for data module.

So now we only need to modify the data_module part in the MPRfile class initialization :
```
if data_module["version"] == 0:
    # If EC-Lab version >= 11.50, column_types is [0 1 0 3 0 174...] instead of [1 3 174...]
    if np.frombuffer(data_module["data"][5:6], dtype="u1").item():
        column_types = np.frombuffer(data_module["data"][5:], dtype="u1", count=n_columns)
        column_types = column_types[1::2]
        remaining_headers = data_module["data"][5 + n_columns : 100]
        main_data = data_module["data"][100:]
   else:
        column_types = np.frombuffer(data_module["data"][5:], dtype="u1", count=n_columns * 2)
        column_types = column_types[1::2]  # suppressing zeros in column types array
        # remaining headers should be empty except for byte 1006 which is == 1
        remaining_headers = data_module["data"][5 + n_columns * 2 : 1006]
        main_data = [data_module["data"][1007:]]
```
I think that's all

**Comment by ml-evs** [comment] 2024-01-18 10:43
> My way of tweaking it and stay compatible with earlier versions was to define 2 different VMPmodule_hdr :
> ...
> I think that's all

Thanks for this @jojo-Li2! Would you be happy to prepare a PR with these changes (I can review and merge it and help with tests)? Otherwise I can have a go myself.

**Comment by jojo-Li2** [comment] 2024-01-18 10:57
Yes I can try and maybe I'll ask for help because I'm still new with the git workflow.
I also worked on loading data from the log and loop files for the case of unfinished experiment. Should I send the modifications in another pull request ? keeping the different subjects appart ?

**Comment by ml-evs** [comment] 2024-01-18 11:02
> Yes I can try and maybe I'll ask for help because I'm still new with the git workflow. I also worked on loading data from the log and loop files for the case of unfinished experiment. Should I send the modifications in another pull request ? keeping the different subjects appart ?

Great! Please do keep them separate for now -- if you push whatever you have we can work through it in the comments of a PR. 

Just to over-explain (sorry if you are already familiar with these steps), you'll need to:
1. make a fork of the repository under your account on GitHub, 
2. commit and push your changes to a branch (it could be your copy of `master` or a branch called `eclab115` or whatever of your choosing) -- if you're not using the git command-line for this then simply uploading and replacing the files in your fork with the new versions on the GitHub page for your fork will also work fine
3. make the pull request from your fork branch to `master` of this repo. Hopefully this will trigger all the automated tests and we can figure out where to go from there (including adding new tests cases).

**Comment by ml-evs** [comment] 2024-02-07 12:27
Thanks to @JhonFlash3008's work (and @chatcannon's help), I think we can close this issue! If you install from this repository you should be able to parse the MPR files from the latest ECLab, and hopefully @chatcannon can prepare another release soon. If you run into any problems please raise a specific issue with as much detail as possible about the file, your setup, and any errors.

**Closed by ml-evs** 2024-02-07 12:27 UTC
